// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACiwWrkSoA5_LIs-5kr1ukgNVes0pkmqg',
    appId: '1:898835974781:web:587d410b4af74458f97f14',
    messagingSenderId: '898835974781',
    projectId: 'kapetayo-delivery',
    authDomain: 'kapetayo-delivery.firebaseapp.com',
    storageBucket: 'kapetayo-delivery.firebasestorage.app',
    measurementId: 'G-SBNWFN67JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4vo5d4jkCq6KWhn9t7L-m070oxag07Oc',
    appId: '1:898835974781:android:f9751edc346e7280f97f14',
    messagingSenderId: '898835974781',
    projectId: 'kapetayo-delivery',
    storageBucket: 'kapetayo-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWUh0OCcU8b-3pHsUaKKksjh5P0uN3I2o',
    appId: '1:898835974781:ios:3e92471d248161baf97f14',
    messagingSenderId: '898835974781',
    projectId: 'kapetayo-delivery',
    storageBucket: 'kapetayo-delivery.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWUh0OCcU8b-3pHsUaKKksjh5P0uN3I2o',
    appId: '1:898835974781:ios:3e92471d248161baf97f14',
    messagingSenderId: '898835974781',
    projectId: 'kapetayo-delivery',
    storageBucket: 'kapetayo-delivery.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACiwWrkSoA5_LIs-5kr1ukgNVes0pkmqg',
    appId: '1:898835974781:web:b03bb0ebab2ced26f97f14',
    messagingSenderId: '898835974781',
    projectId: 'kapetayo-delivery',
    authDomain: 'kapetayo-delivery.firebaseapp.com',
    storageBucket: 'kapetayo-delivery.firebasestorage.app',
    measurementId: 'G-B5KWKWBX84',
  );

}